# Spring Boot Application
spring:
  application:
    name: hello-dubbo-service-user-provider

# UserService service version
user:
  service:
    version: 1.0.0


#自定义配置
embedded:
  zookeeper:
    ## zookeeper 服务连接端口
    port: 2181

# Dubbo Config properties
dubbo:
  scan:
    basePackages: com.example.hello.dubbo.service.user.provider.api
  ## ApplicationConfig Bean
  application:
    id: hello-dubbo-service-user-provider
    name: hello-dubbo-service-user-provider
    qos-port: 22222
    qos-enable: true

  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
    serialization: kryo
    # optimizer: 需要被序列化的类注册到 dubbo 系统中，的回调接口

  provider:
    loadbalance: roundrobin

  ## RegistryConfig Bean
  registry:
    id: zookepper
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}


# Enables Dubbo All Endpoints
management:
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
        ## StatusChecker Name extras (default : empty )
        extras: load,threadpool







